
- hosts: all
  tasks:
    - name: Copy build directory
      copy:
        src: build
        dest: /tmp

    - name: Build haproxy docker image
      docker_image:
        name: haproxy_helloworld
        path: /tmp/build
        force: yes

    - name: Run haproxy docker container
      docker_container:
        name: haproxy_helloworld
        image: haproxy_helloworld
        published_ports: 8000:8000
        restart: yes
        
# vim: set ts=2 sts=2 sw=2 et filetype=yaml:
