
- hosts: all
  tasks:
    - name: Copy config directory
      copy:
        src: config/
        dest: /tmp/haproxy_hello

    - name: Run haproxy docker container
      docker_container:
        name: haproxy_hello
        image: haproxy:1.8.13
        published_ports: 8000:8000
        restart: yes
        volumes:
          - /tmp/haproxy_hello:/usr/local/etc/haproxy/
        
# vim: set ts=2 sts=2 sw=2 et filetype=yaml:
